apiVersion: v1
kind: Service
metadata:
  name: telecom-bot-service
spec:
  selector:
    app: telecom-bot
  type: NodePort
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001